name: CI/CD Pipeline

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
  workflow_dispatch:

env:
  NODE_VERSION: 22.18.0

jobs:
  setup:
    name: 🧩 Setup and Validate
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-deps.outputs.cache-hit }}
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache node_modules
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install Dependencies
        run: npm ci

      - name: Run Lint + Type Check
        run: npm run validate

      - name: Save Installed Modules
        uses: actions/upload-artifact@v4
        with:
          name: node_modules
          path: node_modules/

  tests:
    name: 🧪 Unit + E2E Tests
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-type: [unit, e2e]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Download Cached node_modules
        uses: actions/download-artifact@v4
        with:
          name: node_modules
          path: node_modules/

      - name: Prepare for Playwright (only if e2e)
        if: matrix.test-type == 'e2e'
        run: npx playwright install --with-deps

      - name: Run Tests
        run: |
          if [ "${{ matrix.test-type }}" = "unit" ]; then
            npm test -- --coverage;
          else
            npm run test:e2e;
          fi

  build:
    name: 🏗️ Build App
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: actions/download-artifact@v4
        with:
          name: node_modules
          path: node_modules/

      - name: Build Production
        run: npm run build:production

      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build/

  deploy:
    name: 🚀 Deploy to Vercel
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build
          path: build

      - name: Deploy with Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
